import Head from 'next/head'
import AddTask from '../components/AddTask'
import Header from '../components/Header'
import TasksList from '../components/TasksList'

export default function Home() {
  return (
    <div className="bg-gray-200 min-h-screen">
      <Head>
        <title>Task Man</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <AddTask />
      <TasksList />
    </div>
  )
}
